version: 0.2

env:
  parameter-store:
    URLS: "/health-check-urls"

phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - echo "Starting URL checks..."
      - python check_urls.py

artifacts:
  files:
    - results.json
